### ISSUE TITLE
Lower Jig v3.0 Fitment Issues

### ISSUE THREAD

**Issue by Realsasquatch** [swolebro/swolebro-youtube#1]
After watching your video I noticed that the two side plates needed some minor adjustments... beveled the edges as you suggested but around the trigger pocket area there doesn't seem to be any clearance issues but more over the side plate thickness itself. Are the plates supposed to touch at the trigger area? 
When putting the jig together is the drill guide to be flush with the back plate and same for the trigger pocket top plate? Reason I ask is there seems to be some alignment issues. 
My lower is coated so I am thinking I am going to scribe out the trigger pocket and double check the placement vs the cad measurements. Did you have any issues in this area when you started?
My thanks for putting these plans up and taking the time to answer a few questions...  total lifesaver that you will never truly know just how much so.

Cheers,
Chad.

**Comment by swolebro** [comment]
Hm, when clamping the two side plates around the lower, I'd expect there to be a _very slight_ gap in the trigger guard area (which you might shim with a bit of paper, foil, etc. until you can get good and even clamping). The width of a lower in that back area varies from part to part, since it's a non-critical dimension on a casting.

I based my CAD dimensions on that by looking at the ones I had on hand, subtracting 30 thou or so from the thinnest one, and then dividing it by two. If yours end up being even thinner, and it's causing you to get a loose fit, you can always sand those two surfaces down a bit.

For the drilling and milling guides, yes, they should butt up against the back plate. Can you please elaborate on the alignment issues you're seeing there?

And yes, I'd encourage you to sanity-check my work as you go. I haven't gotten to put the v3.0 to use yet, but the critical template dimensions were copied over directly from the v2.0 (so they should be good). The only difference was v2.0 was meant to used with a laser cutter and drill press, whereas v3.0 is suited for a 3D printer and a router. If you want to scribe out the pocket, I'd recommend printing a copy of the milling template and stopping the print after 5-10 layers. That way you'll have a thinner piece to work with, and a much easier inspecting it and getting your scribe in there.


Also, in case you were wondering, the hole that's off to one side on the milling template... that's so you can scribe a line 1.250" down on the matching side plate, and stick the endmill through the hole to check when you're getting close to the final depth. More stuff that should make more sense once I get around to the video.

**Comment by Realsasquatch** [comment]
LOL... it's funny cause that hole you mention on the side I figured out on
my own... I was like hmmm this would make it easy to measure my depth
with...lol, great idea by the way.  I have also come up with an upgrade for
your next version.... if you don't mind that is. where you have the holes
where you suggest tapping you should put a slot about a quart of the way
down the length of the hole. This way you can slide a nut inside the hole
to thread the bolt/screw to. No more tapping required and it makes the
connection way more secure and gets rid of the chance of stripping the
thread in the pla. My alignment issue I think came from a printing issue on
my end, looks like one of my prints was a bit warped due to an adhesion
problem. I've since re printed those parts and it looks like everything is
lining up pretty good. I will let you know for sure once I get the scribe
mark down and take some measurements. I'm just waiting for my endmill bits
to arrive so I can get started on the work.

Cheers,
Chad.

**Comment by swolebro** [comment]
Ooooh, just a drop in slot for a nut, I like that. That should be easy to add. And it'd probably take less time to do in CAD than it'd take to tap the threads!

Good shit, man. Keep the feedback coming once you've put the thing to use.

**Comment by Realsasquatch** [comment]
Hey man... put everything together today and checked the pocket template.... it was way off... too far forward to the point it was almost at the bolt release wall. If you put the milling guide against the back plate it also makes it go cockeyed to the left. Looks like it is going to have to be adjusted a bit to get the pocket in the right location.

**Comment by swolebro** [comment]
I scribed out my own test piece and confirmed that the pocket jig does sit too far forward on this one. Well, fuck. Gonna need to dig into the CAD and see what dimension got out of whack. I'll comment back once I've got that done/updated Thingiverse. Not sure if I can update the ZIP file on LBRY, but I'll at least be able to change the post description.

As for it being cockeyed, I'm definitely not seeing that. Have you checked to see if your printer left any overextrusion on the corners or whatnot? That could be bumping one side forward.

Thank you for catching the pocket placement. Sure enough, crowd sourcing help is part of why I open sourced it, and the fact that it is open source is why I recommend measuring twice and cutting once. lol

**Comment by swolebro** [comment]
FYI, I scribed out the pocket on a new model and it looks good now. Also tweaked some of the tight spots around the trigger area and the buffer tube (the stuff from the original video). The Thingiverse page has been updated with the new ones, and LBRY got a new upload. (Can't edit the original one in-place.)

Printing off a new drilling guide and full-size router guide now... and cleaning my shop so I can finally shoot the tutorial video. Hah.

If I encounter any other fuckups in doing the video then I'll post a v3.2.

**Comment by Realsasquatch** [comment]
Awesome... sounds great... looking forward to seeing the new video and lower once it's all milled out.

**Comment by swolebro** [comment]
Gonna take a swing at editing the video this weekend. Already shot it all (very pleased with the final product), but now have to sift through 100GB of video and make something coherent out of it. Yayyyyyy. I expect that alone will be 20hrs of work.

**Comment by swolebro** [comment]
FYI, videos are up on LBRY/Odysee now. Covers it in pretty gory detail, but let me know if anything is left unclear.

Figure when I get around to doing a v3.2 and making another lower, I'll shoot another video with no narration/explanation/etc, just running through the steps in brief. That won't be for a while, though. Got enough projects to handle right now, and this should be enough for people to work with.

**Comment by Realsasquatch** [comment]
video 3 won't load

**Comment by swolebro** [comment]
Well, that's just dandy. Looks like it'll still play on the computer that I originally uploaded it from (because it has it cached locally), but it didn't propagate to other servers on the network. Could be the file size causing an issue, since I've seen large non-video files crap out via the Odysee website before.

I'll dig into it. Easiest thing might be to just split into a fourth part, re-render, and reupload.

**Comment by swolebro** [comment]
Figured it out. Funny backend stuff when using the LBRY client to upload content vs. the YouTube sync feature.

I was able to play it off the Odysee webpage now - give it a shot and let me know if it works for you as well.

**Comment by Realsasquatch** [comment]
Hey Swolebro ... yeppers that worked great... was able to watch the video. Interesting about the detent issue and the workaround for that.. good bit of info. there. On another note... I did find another STL for a jig... one with the slots in it, the problem with that jig was that the upper block was not made tall enough or wide enough in my opinion to use a router. But I was able to tinker with it a bit and got it raised up high enough to use a router... it could stand to be a bit wider though. I checked it in comparison with your router platform and your holes were just a bit off to be able to use your router table from your jig. I was going to put a link in for the other jig but it seems to have been removed. I do however have the file if you would like it, I thought you might be able to do a remix and either widen and raise the table height on their jig set or remix it to be able to be used with yours...Cheers, Chad.

**Comment by swolebro** [comment]
You talking about the CTRLPew one? Yeah, a friend showed me that one recently. No fucking way am I going to deal with remixing somebody else's SolidWorks parts though. lol

I uploaded a v3.2beta8 FCStd up on the Thingiverse page [here](https://www.thingiverse.com/thing:4632613). This one includes slots for nuts. I'll be honest, I'm not sold on the idea. With the takedown pin holes and the drill holes, there's not a lot of room for these slots. I'd like to incorporate some sort of bushing system in for the pilot holes, and with the space that'd take, it'd be mutually exclusive.

Anyway, give that a shot. You'll need to export the STL's from FreeCAD yourself, since I'm not gonna overwrite the current ones on Thingiverse. Also incorporated the other tweaks like bumping the pocket size out 0.003", adding notches for sighting the alignment, and giving the trigger slot guide more clearance to avoid melting.

**Comment by swolebro** [comment]
Gonna mark this ticket as resolved.

As demonstrated in the v3.1 videos, the fitment problems with v3.0 were fixed, and I'm now moving on to v3.2.
