### ISSUE TITLE
Connect to MACH3

### ISSUE THREAD

**Issue by PaulKusch** [swolebro/swolebro-youtube#6]
Hi!
  I just made your sketch! It works very well, but it does not give the commands to MACH3. I suppose that is a Mach3 problem, the command appears in MACH3 in "Diagnostics" menu, but there have no reaction in axis z as response to these commands (UP/DOWN). Have You any ideea how to set up MACH3? Or maybe another user that follow your sketch have any idea, how to do the right way?

 Thanks in advance!

**Comment by swolebro** [comment]
Unfortunately, I have zero experience with Mach 3. I try to avoid proprietary software like the plague, especially if it's Windows-based.

Just throwing it out there, the desktop computer I ran LinuxCNC on was _cheap_ and _old_. The hardware requirements are _very_ minimal. Basically any machine with a parallel port will work. If you want to experiment with it, you could get a dedicated computer, swap the wiring from your Mach machine, and follow my LinuxCNC basics + HAL videos. Then if you want to go back to Mach, you swap the wiring back over. It's a time investment, but otherwise low risk.
